project:
  type: website

website:
  title: "Amanpreet Kaur"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: assignments.qmd
        text: Assignments

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

